### ISSUE TITLE
homebride error while loading plugin

### ISSUE THREAD

**Issue by elfnino** [MacWyznawca/homebridge-mqtt-power-consumption-log-tasmota#1]
[4/4/2017, 11:53:52 AM] ====================
[4/4/2017, 11:53:52 AM] ERROR LOADING PLUGIN homebridge-mqtt-power-consumption-log-tasmota:
[4/4/2017, 11:53:52 AM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)

**Comment by MacWyznawca** [comment]
@elfnino 
In version 0.9.1 I've added 'use strict', let me know if it helped.

**Comment by elfnino** [comment]
Thank you it helped !
