### ISSUE TITLE
ReferenceError: data is not defined

### ISSUE THREAD

**Issue by elfnino** [MacWyznawca/homebridge-mqtt-power-consumption-log-tasmota#2]
Hi, I have used a standart config and I am getting following error:

[5/3/2017, 10:17:05 PM] Loaded plugin: homebridge-mqtt-power-consumption-log-tasmota
[5/3/2017, 10:17:05 PM] Registering accessory 'homebridge-mqtt-power-consumption-log-tasmota.mqtt-power-consumption-log                           -tasmota'
[5/3/2017, 10:17:05 PM] ---
[5/3/2017, 10:17:06 PM] Loaded plugin: homebridge-mqtt-switch-tasmota
[5/3/2017, 10:17:06 PM] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[5/3/2017, 10:17:06 PM] ---
[5/3/2017, 10:17:06 PM] Loaded config.json with 1 accessories and 0 platforms.
[5/3/2017, 10:17:06 PM] ---
[5/3/2017, 10:17:06 PM] Loading 0 platforms...
[5/3/2017, 10:17:06 PM] Loading 1 accessories...
[5/3/2017, 10:17:06 PM] [prvePOW] Initializing mqtt-power-consumption-log-tasmota accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ââââââââââââââ
    â 031-45-154 â
    ââââââââââââââ

[5/3/2017, 10:17:06 PM] Homebridge is running on port 51826.
[5/3/2017, 10:17:06 PM] [prvePOW] Nothing to change _hourly
[5/3/2017, 10:17:06 PM] [prvePOW] Nothing to change _daily
[5/3/2017, 10:17:06 PM] [prvePOW] Nothing to change _period
**/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:398
                        data = null;
                             ^

ReferenceError: data is not defined**
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:398:9                           )
    at emitThree (events.js:116:13)
    at MqttClient.emit (events.js:194:7)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_module                           s/mqtt/lib/client.js:821:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules                           /mqtt/lib/client.js:286:12)
    at process (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.                           js:242:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules                           /mqtt/lib/client.js:252:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-stream/                           lib/_stream_writable.js:338:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-s                           tream/lib/_stream_writable.js:327:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-                           stream/lib/_stream_writable.js:264:11)

**Comment by elfnino** [comment]
#config.json :

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",

    "platforms": [],

        "accessories": [

                {
                        "accessory": "mqtt-power-consumption-log-tasmota",

                        "name": "prvePOW",

                        "url": "mqtt://127.0.0.1",
                        "username": "stano",
                        "password": "stano",

                        "topics": {
                                "statusGet": "stat/sonoffPOW1/POWER",
                                "statusSet": "cmnd/sonoffPOW1/power",
                                "energyGet": "tele/sonoffPOW1/ENERGY",
                                "stateGet": "tele/sonoffPOW1/STATE"
                        },
                        "onValue": "ON",
                        "offValue": "OFF",

                        "outletInUseBy": "current",
                        "outletInUseCurrent": "0.01",

                        "totalPowerResetBy": "month",

                        "activityTopic": "tele/sonoffPOW1/LWT",
                        "activityParameter": "Online",

                        "startCmd": "cmnd/sonoffPOW1/TelePeriod",
                        "startParameter": "15",

                        "patchToSave":"/home/pi/",
                        "savePeriod": "15",

                        "manufacturer": "ITEAD",
                        "model": "Sonoff TH",
                        "serialNumberMAC": "5C:CF:7F:92:D2:15"
                }



        ]
}

**Comment by elfnino** [comment]
Any idea whether it is a bug ? Or should I focus on something else troubleshooting  ?

**Comment by elfnino** [comment]
Any suggestion what could be wrong ?

**Comment by swilalaa** [comment]
+1 Same issue here

**Comment by zhilly** [comment]
i have the same +2

**Comment by AntiHeld889** [comment]
i have the same +3

**Comment by ceraz68** [comment]
Hi I also get the same issue. Seems to be linked to the URL statement in json file. I'm running mosquitto server on the synology with homebridge within docker. Tried "url" as "mqtt://IP_address" or "mqtt://IP_address:1883" or "IP_address".

Has someone found a workaround or explanation ?

**Comment by ceraz68** [comment]
I validated my MQTT setup using the homebridge-mqtt-switch-tasmota plugin which works fine.
For the homebridge-mqtt-power-consumption-log-tasmota plugin I got access errors as the log files try to write to /root/.homebridge so I changed to the docker folder. When they were resolved back to the original error
**/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:398
data = null;
^

**Comment by Giorgiofox** [comment]
same error here:
/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:398
			data = null;
        ^
ReferenceError: data is not defined
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:398:9)
    at emitThree (events.js:116:13)
    at MqttClient.emit (events.js:197:7)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.js:935:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)

**Comment by Giorgiofox** [comment]
Solved:
https://github.com/MacWyznawca/homebridge-mqtt-power-consumption-log-tasmota/pull/4/commits
